export const FETCH_SERVER_START = "SERVER_START";
export const FETCH_SERVER_SUCCESS = "SERVER_SUCCESS";
export const FETCH_SERVER_ERROR = "SERVER_ERROR";

export const GET_COIN_START = "GET_COIN_START ";
export const GET_COIN_SUCCESS = "GET_COIN_SUCCESS ";
export const GET_COIN_ERROR = "GET_COIN_ERROR ";